version: '2'

services:

#-------------------------------------------------------------------
# DOOM 2
#-------------------------------------------------------------------
  doom2:
    build:
      context: .
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERNAME}:/home/${USERNAME}
    environment:
      - PATH_DOOM2=${PATH_DOOM2}
    networks:
      - backend

#-------------------------------------------------------------------
# NETWORK SETUP
#-------------------------------------------------------------------
networks:
  backend:
    driver: "bridge"

#-------------------------------------------------------------------
# VOLUME SETUP
#-------------------------------------------------------------------
volumes:
  doom2:
    driver: "local"