version: '2'

services:

#-------------------------------------------------------------------
# WINE
#-------------------------------------------------------------------
  wine:
    build:
      context: .
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USERNAME=${USERNAME}
      - WINEARCH=${WINEARCH}
      - WINEDEBUG=${WINEDEBUG}
    networks:
      - backend

#-------------------------------------------------------------------
# NETWORK SETUP
#-------------------------------------------------------------------
networks:
  backend:
    driver: "bridge"

#-------------------------------------------------------------------
# VOLUME SETUP
#-------------------------------------------------------------------
volumes:
  wine:
    driver: "local"